# Generated by Django 2.1.1 on 2018-09-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together={('invite_token', 'email')},
        ),
    ]
