# Generated by Django 2.1.1 on 2018-09-07 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_manager', '0002_auto_20180906_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
    ]
