version: '2'

services:
  db:
    image: postgres:latest
    container_name: deviceactivity_db01
    volumes:
    - ./runtime/postgres_data:/var/lib/postgresql/data:Z
    ports:
    - "5435:5432"
    environment:
    - POSTGRES_PASSWORD=qwerty
    - POSTGRES_DB=activity_device

  redis:
    image: redis
    container_name: deviceactivity_redis01
    ports:
    - "6382:6379"
    volumes:
    - ./runtime/redis:/data:Z

  web:
    build: .
    container_name: deviceactivity_app01
    command: bash -c "python3 /code/manage.py migrate --noinput && python3 /code/manage.py runserver 0.0.0.0:8000"
    depends_on:
    - db
    - redis
    ports:
    - "8080:8000"
    volumes:
    - .:/code

  celery:
    build: .
    container_name: deviceactivity_celery01
    command: celery -A device_activity worker -l info
    volumes:
    - .:/code
    depends_on:
    - db
    - redis
    - web