# Generated by Django 2.1.1 on 2018-09-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associate', '0002_device_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
