# Generated by Django 2.1.1 on 2018-09-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associate', '0005_auto_20180907_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_synchronization',
            field=models.DateTimeField(null=True),
        ),
    ]
