# Generated by Django 2.1.1 on 2018-09-19 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_user(apps, schema_editor):
    Activity = apps.get_model('associate', 'Activity')
    for activity in Activity.objects.all():
        activity.user = activity.device.user
        activity.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('associate', '0006_device_last_synchronization'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(add_user),
    ]
