# Generated by Django 2.1.1 on 2018-09-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180907_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_synchronization',
            field=models.DateTimeField(null=True),
        ),
    ]
